export const CREATE_REMINDER = "CREATE_REMINDER";
export const DELETE_REMINDER = "DELETE_REMINDER";
export const UPDATE_REMINDERS = "UPDATE_REMINDERS";
export const DELETE_ALL_REMINDERS_BY_DATE = "DELETE_ALL_REMINDERS_BY_DATE";

